config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|de|uk|ru|fr|it|es|pt/ do

    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
    devise_for :users, controllers: {
      sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations',
      passwords: 'users/passwords', unlocks: 'users/unlocks'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :hosts, except: [:index] do
      collection do
        get 'finished_signup'
      end
    end

    resources :pages, only: [:index] do
      collection do
        get 'about'
        get 'faq'
        get 'next_steps'
        get 'data_privacy'
        post 'export_my_data'
        get 'legal'
      end
    end

    get 'verifications/new' => 'verifications#new', as: :new_verification
    get 'verifications/no_phone' => 'verifications#no_phone_verify', as: :no_phone_verify
    post 'verifications/do_id_verify' => 'verifications#do_id_verify', as: :do_id_verify
    post 'verifications/send' => 'verifications#do_send_pin', as: :send_verification
    post 'verifications/check' => 'verifications#check', as: :check_verification
    get 'verifications/review' => 'verifications#review', as: :review_verifications
    match 'verifications/verify_member/:id' => 'verifications#verify_member', as: :verify_member, via: [:get, :post]
    match 'verifications/reject_verification/:id' => 'verifications#reject_verification', as: :reject_verification, via: [:get, :post]

    root to: "pages#index"

  end
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_not_yet_verified, except: [:review, :review_from_payments, :verify_member, :reject_verification]
  #before_action -> { require_privilege('help_single_user') }, only: [:review, :review_from_payments, :verify_member, :reject_verification]

  def new
    @mobile = current_user.guess_country_code(current_user.mobile.standardise_phone_number, true) if current_user.mobile
    #if (params[:show] != 'true') and (!current_user.country.blank?) and not current_user.in_Europe?
      #@nonEU = true
      #render 'no_phone_verify' and return
    #end
  end

  #def no_phone_verify
  #end

  def do_send_pin
    mobile = params[:mobile].standardise_phone_number
    mobile = current_user.guess_country_code(mobile, false)
    send_error = false

    begin
      if (mobile != current_user.mobile and ConfirmedPhoneNumber.mobile_number_available?(mobile)) # user supplied a different number here!
        current_user.mobile = mobile
        current_user.save
        ConfirmedPhoneNumber.where(:phone_no => mobile).first_or_create(:user_id => current_user.id)
        current_user.generate_phone_pin
        current_user.send_phone_pin
      elsif mobile != current_user.mobile and not ConfirmedPhoneNumber.mobile_number_available?(mobile)
        flash.now[:alert] = I18n.t('verify.explanation_unique_number')
        render :js => "window.location = '#{new_verification_path}'" and return
      else
        current_user.generate_phone_pin
        current_user.send_phone_pin
      end
    rescue
      flash.now[:alert] = I18n.t('verify.pin_not_sent')
      render :js => "window.location = '#{new_verification_path}'" and return
    end

    respond_to do |format|
      format.js # render app/views/verifications/do_send_pin.js.erb
    end
  end

  def check
    if current_user.mobile == params[:hidden_phone_number].standardise_phone_number
      current_user.verify_phone_pin(params[:pin])
      if current_user.verified_phone? # Success!!
        UserMailer.welcome(current_user, I18n.locale).deliver_later
      end
    # notification of success/fail will be handled by Javascript
    else
      flash.now[:alert] = I18n.t('verify.number_not_match')
      redirect_to :new_verification and return
    end
    respond_to do |format|
      format.js
    end
  end

  protected

  def ensure_not_yet_verified
    if current_user.verified_phone?
      flash[:notice] = I18n.t('verify.already_verified')
      redirect_to '/'
    #elsif !current_user.confirmed?
      #flash[:alert] = I18n.t('verify.email_first') + ' ' + view_context.link_to(new_user_confirmation_url, new_user_confirmation_url, style: 'color: white')
      #redirect_to '/'
    end
  end

end

app/views/verifications/check.js.erb
$('#status-box').hide();
<% if current_user.verified_phone? %>
  $('#verify-pin').hide();
  $('#status-box').removeClass();
  $('#status-box').addClass('alert alert-success');
  $('#status-message').text("<%= t('general.success').html_safe %>");
  $('#status-box').show();
  $('#go_on_now').show();
  $('#link_dashboard').show();
<% else %>
  $('#status-box').removeClass();
  $('#status-box').addClass('alert alert-warning');
  $('#status-message').text("<%= t('verify.pin_not_right').html_safe %>");
  $('#status-box').show();
  $('#link_dashboard').hide();
<% end %>
$('#status-box').fadeIn();

app/views/verifications/do_send_pin.js.erb
$('#hidden_phone_number').val('<%= current_user.mobile %>' );
$('#send-pin').hide();
$('#verify-pin').fadeToggle();
$('#pin').focus();

app/views/verifications/new.html.erb
<h2><%= t("verify.headline") %></h2>

<noscript>
  <div class="internal-alert">
    <p>Please activate Javascript, otherwise this page won"t work.</p>
  </div>
</noscript>

<div class="mobile-verify--icon--container">
  <svg class="mobile-verify--icon" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 100 125" enable-background="new 0 0 100 100" xml:space="preserve"><path d="M62.642,5.45C59.239,4.994,50.695,5,50.695,5h-0.598c0,0-8.552-0.006-11.95,0.45  c-5.94,0.808-10.481,0.713-10.481,12.19c0,3.884,0,62.091,0,67.835c0,5.748,4.84,9.524,11.216,9.524s11.216,0,11.216,0h0.598  c0,0,4.84,0,11.216,0c6.372,0,11.208-3.776,11.208-9.524c0-5.744,0-63.951,0-67.835C73.119,6.164,68.59,6.258,62.642,5.45z   M45.863,7.87h8.566c0.303,0,0.553,0.246,0.553,0.558c0,0.299-0.25,0.552-0.553,0.552h-8.566c-0.307,0-0.557-0.253-0.557-0.552  C45.307,8.116,45.557,7.87,45.863,7.87z M55.485,91.174c0,0.466-0.382,0.855-0.851,0.855h-8.469c-0.477,0-0.859-0.39-0.859-0.855  v-1.218c0-0.466,0.383-0.852,0.859-0.852h8.469c0.469,0,0.851,0.386,0.851,0.852V91.174z M69.597,83.005H30.795V15.082h38.802  V83.005z"/></svg>
</div>

<div id="status-box" class="alert alert-success" style="margin-top: 10px; font-size: 22px; margin-left: -15px; display: none;">
  <p id="status-message"><%= t("general.status_nothing") %></p>
  <p id="go_on_now" style="display: none;"><%= t("verify.thanks_verified") %></p>
  <p id="link_dashboard" style="display: none;"><%= link_to t("buttons.go_to_dashboard"), finished_signup_hosts_path, :class => "btn btn-primary" %></p>
</div>

<div id="send-pin">
<%= form_tag send_verification_path, remote: true do |f| %>
  <p class="intro-text--internal" style="display: none">
    <%= t("verify.what_phone") %> <%= t("verify.phone_explanation") %>
  </p>

  <div class="verify--strap row">
    <div class="col-md-6">
      <p class="mobile-verify"><%= t("verify.what_phone") %></p>
    </div>
    
    <div class="col-md-6">
      <%= text_field_tag :mobile, @mobile, placeholder: "+00 0000 000 000", class: "form-control", style: "margin-top: 7px;margin-bottom: 10px;" %>
      <p class="help-block"><%= t("verify.national_prefix") %> +<%= ISO3166::Country[current_user.country].country_code if ISO3166::Country[current_user.country] %> 11122233344</p>
    </div>
  </div>

  <%= submit_tag t("verify.send_pin_button"), class: "btn btn-danger large-button", id: "send-pin-link" %>
  
  <p class="disclaimer--internal">
    <%= t("verify.disclaimer")  %>
  </p>
  
  <p>&nbsp;</p>
  
  <script>
    $("form").submit(function( event ) {
      if (($("#mobile").val().length < 10) || (!$("#mobile").val().startsWith("+"))) {
        <% if ISO3166::Country[current_user.country] %>
        addtxt = "<%= t("verify.expected_country_code", country: current_user.country_name(true)) %> +<%= ISO3166::Country[current_user.country].country_code %> .";
        <% else %>
        addtxt = "<%= t("verify.expected_plus") %>";
        <% end %>
        proceed = confirm("<%= t("verify.include_prefix") %> " + addtxt + " <%= t("verify.click_cancel") %>");
        return proceed;
      }
    });
  </script>
  
<% end %>
</div>

<div id="verify-pin" style="display: none;">
<%= form_tag check_verification_path, remote: true do |f| %>
  <%= hidden_field_tag "hidden_phone_number", "" %>

  <div class="verify--strap row">
    <div class="col-md-6">
      <p class="mobile-verify"><%= t("verify.enter_pin") %></p>
    </div>
    
    <div class="col-md-6">
      <%= text_field_tag :pin, "", class: "form-control", style: "width: 100px; font-size: 22px; height: 40px; margin-top: 10px;" %>
    </div>
  </div>
 
  <%= submit_tag t("verify.verify_pin_button"), class: "btn btn-danger large-button" %>
 
  <p style="text-align: center"><%= link_to t("verify.resend_pin_button"), new_verification_path %></p>
  
  <p class="disclaimer--internal" style="padding: 0 0 0">
    <%= t("verify.disclaimer")  %>
  </p>
  
<% end %>
</div>

<style>
#no-ver-link {
    position: relative;
    top: -150px;
    left: 250px;
    padding-left: 10px;
    padding-right: 10px;
    display: inline;
    z-index: 1;
}
</style>