config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|de|uk|ru|fr|it|es|pt/ do

    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
    devise_for :users, controllers: {
      sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations',
      passwords: 'users/passwords', unlocks: 'users/unlocks'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :hosts, except: [:index] do
      collection do
        get 'finished_signup'
      end
    end

    resources :pages, only: [:index] do
      collection do
        get 'about'
        get 'faq'
        get 'next_steps'
        get 'data_privacy'
        post 'export_my_data'
        get 'legal'
      end
    end

    get 'verifications/new' => 'verifications#new', as: :new_verification
    get 'verifications/no_phone' => 'verifications#no_phone_verify', as: :no_phone_verify
    post 'verifications/do_id_verify' => 'verifications#do_id_verify', as: :do_id_verify
    post 'verifications/send' => 'verifications#do_send_pin', as: :send_verification
    post 'verifications/check' => 'verifications#check', as: :check_verification
    get 'verifications/review' => 'verifications#review', as: :review_verifications
    match 'verifications/verify_member/:id' => 'verifications#verify_member', as: :verify_member, via: [:get, :post]
    match 'verifications/reject_verification/:id' => 'verifications#reject_verification', as: :reject_verification, via: [:get, :post]

    root to: "pages#index"

  end
end

app/views/pages/about.de.html.erb
<script>
  $( document ).ready(function() {
    console.log( "jQuery is functional." );
  });
</script>

<h3  mb-1>Safehost</h3>
<div class="">
<p style="font-family:verdana; color:#24d6ab;">Diese Webseite wurde entwickelt, um Gastgeber:innen von Unterbringungen mit Geflüchteten zusammenzubringen. Während es Dutzende solcher Seiten gibt, wurde dieses bottom-up entwickelt, das heißt unter Berücksichtigung der Bedürfnisse der Freiwilligen vor Ort im LAF <a href="https://www.berlin.de/laf/">(Landesamt für Flüchtlingsangelegenheiten)</a>, einem der Berliner Ankunftszentren für Geflüchtete. Die Sicherheit wird dadurch erhöht, dass i) die Telefonnummer des Gastgebers oder der Gastgeberin durch einen per SMS verschickten Code verifiziert wird und ii) die ID- oder Passnummer des Gastgebers oder der Gastgeberin bei der Begrüßung/Abholung vor Ort gespeichert und von Freiwilligen überprüft wird.</p>

<p>Zurzeit werden die Geflüchteten <b>von den Gastgeber:innen persönlich im LAF</b> abgeholt.</p>
<p>Das Ziel dieser Webseite ist es, insbesondere:</p>
<ol type="i">
<li> die Bereitstellung von sicheren Unterkünften durch das Verifizierungssystem zu unterstützen;</li>
<li> den Abgleich zwischen den beim LAF ankommenden Geflüchteten und den Gastgeber:innen, die vor Ort Unterkünfte anbieten, zu unterstützen;</li>
<li> bessere Datensicherheit als die bisherigen GoogleForms, einschließlich einer besseren Einhaltung der Datenschutz-Grundverordnung, beispielsweise durch Speicherung auf deutschen Servern, und</li>
<li> Sichtbarkeit und Vertrauen in die Authentizität der Lösung zu ermöglichen. Viele Menschen waren misstrauisch, ein einfaches GoogleFormular zu verwenden, ohne zu wissen, an wen die Daten wirklich weitergegeben würden.</li>
</ol>

<p class="mb-5">Diese Webseite wird zunächst nur von der privaten Initiative Accomodation for Refugees genutzt, die ehrenamtlich vor Ort beim LAF tätig ist. Sie bringt Geflüchtete, die vor Ort ankommen, mit Gastgeber:innen zusammen. In den vergangenen Tagen wurden bereits mehr als 140 Unterkünfte vermittelt.</p>

app/views/pages/about.en.html.erb
<script>
  $( document ).ready(function() {
    console.log( "jQuery is functional." );
  });
</script>

<h3  mb-1>Safehost</h3>
<p style="font-family:verdana; color:#24d6ab;">is made for bringing together hosts and refugees for accommodation.</p>
<p>While dozens of such tools exist, this one was developed bottom-up in consideration of needs of on-site volunteers at Landesamt für Flüchtlingsangelegenheiten - Berlin (LAF <a href="https://www.berlin.de/laf/">(Landesamt für Flüchtlingsangelegenheiten)</a>)/State Office for Refugee Affairs Berlin, one of Berlin’s arrival centers for refugees. It emphasizes safety by i) verifying host’s phone number through a code sent via SMS, and ii) saving host’s ID or passport number at the time of on-site greeting/pickup, verified by volunteers.</p>

<p>For now, refugees are being picked up <b>by the hosts personally at LAF.</b></p>

<p>The aim of this tool is to specifically:</p>
<ol type="i">
<li> support provision of safer spaces through its verification system;</li>
<li> support on-the-spot-matching for refugees arriving at LAF <a href="https://www.berlin.de/laf/">(Landesamt für Flüchtlingsangelegenheiten)</a>with hosts offering space;</li>
<li> better data security than the previous GoogleForms, including better compliance with GDPR, for example through storage on German servers; and</li>
<li> enable both visibility and trust in the authenticity of the solution. Many people were suspicious of using a simple GoogleForm being shared, without knowing who the data would really go to.</li>
</ol>

<p class="mb-5">The tool initially is only going to be used by the private initiative <a href="https://www.accommodation-for-refugees.com/" class="link-secondary">Accomodation for Refugees</a>, volunteering on-site at LAF. They match refugees who arrive on-site with hosts. In the past days, more than 140 accommodations have been mediated.</p>

app/views/pages/about.html.erb
<script>
  $( document ).ready(function() {
    console.log( "jQuery is functional." );
  });
</script>

<h3  mb-1>Safehost</h3>
<div class="">
<p style="font-family:verdana; color:#24d6ab;">is made for bringing together hosts and refugees for accommodation.</p>
<p>While dozens of such tools exist, this one was developed bottom-up in consideration of needs of on-site volunteers at Landesamt für Flüchtlingsangelegenheiten - Berlin (LAF)/State Office for Refugee Affairs Berlin, one of Berlin’s arrival centers for refugees. It emphasizes safety by i) verifying host’s phone number through a code sent via SMS, and ii) saving host’s ID or passport number at the time of on-site greeting/pickup, verified by volunteers.</p>

<p>For now, refugees are being picked up <b>by the hosts personally at LAF.</b></p>

<p>The aim of this tool is to specifically:</p>
<ol type="i">
<li> support provision of safer spaces through its verification system;</li>
<li> support on-the-spot-matching for refugees arriving at LAF with hosts offering space;</li>
<li> better data security than the previous GoogleForms, including better compliance with GDPR, for example through storage on German servers; and</li>
<li> enable both visibility and trust in the authenticity of the solution. Many people were suspicious of using a simple GoogleForm being shared, without knowing who the data would really go to.</li>
</ol>

<p class="mb-5">The tool initially is only going to be used by the private initiative <a href="https://www.accommodation-for-refugees.com/" class="link-secondary">Accomodation for Refugees</a>, volunteering on-site at LAF. They match refugees who arrive on-site with hosts. In the past days, more than 140 accommodations have been mediated.</p>

app/views/pages/e_404.html.erb
<h2>Not Found</h2>

<p>The content you were looking for could not be found. Maybe you followed an outdated link.</p>

app/views/pages/faq.en.html.erb
<h3 class="header-style mb-3">1. General</h3>



<div class="accordion accordion-flush" id="accordionExample">

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Why another housing site?
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        It is true that the whole housing topic is very confusing. In general, one should distinguish between sites that give data access to:
    <ol type="i" class="">
    <li>official authorities </li>
    <li>volunteers cooperating with official authorities </li>
    <li>volunteers </li>
    <li>refugees directly </li>
    </ol>
    <p class="">They also differ according to the level of ID verification and safety check that is done, and data protection standards adhered to. Have a look at the below table, in which safety is arguably the higher the further away from the lower-right corner. We cannot guarantee accuracy nor accept liability for decisions based on this table:</p>


   <div class="table-responsive">
<table class="table table-secondary table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col" class="fst-italic fs-6">Human safety check<br> / identification</th>
      <th scope="col" class="fst-italic fs-6">Computerized safety check</th>
      <th scope="col" class="fst-italic fs-6">No safety check<br> / identification</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Data used by official authorities</th>
      <td>Possibly unterkunft-ukraine.de</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">Data used by volunteers cooperating with official authorities</th>
      <td><strong>Safehost for Berlin LAF <a href="https://www.berlin.de/laf/">(Landesamt für Flüchtlingsangelegenheiten)</a>.</strong><br>
      Several circulating online forms, often based on Google Forms.</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">Data used by volunteers</th>
      <td>A few local initiatives who step in as mediators between public offers and public requests.</td>
      <td></td>
      <td></td>
    </tr>
<tr>
      <th scope="row">Data used directly by refugees</th>
      <td></td>
      <td>E.g., helppeopleleaveukraine.org or wunderflats.com</td>
      <td>Almost all other platforms, apps, telegram channels.</td>
    </tr>

  </tbody>
</table>
</div>

 <p class="mt-3">Any official authority will require high safety standards when connecting  refugees with hosts. On the other hand, informal sites or media can often be very quick, but come with safety risks, which official authorities will never take. This site aims to fill a gap which was previously filled by online sheet forms, for which it is harder to verify who is behind them.
<br>
(If your site is listed incorrectly above, kindly let us know with suitable evidence.)</p>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Why are there so many of them, anyways?
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Everyone wants to help, including IT people. But there was (and is) no central forum to connect those that operate or plan housing platforms with each other. If you operate or plan such a site and want to informally get in touch, please contact <a href="mailto:matthi@safehost.space" class="text-muted"> matthi@safehost.space </a>.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Can you tell me about the housing site XYZ?
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Not more than what is stated above, sorry.
      </div>
    </div>
  </div>
</div>






<h3 class="header-style mb-3 mt-3" >2. Data and security</h3>



<div class="accordion accordion-flush" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
       What happens to my data?
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
At the technical level: your data is encrypted and stored on our secure server (hosting by Heroku on a Frankfurt-based server). We do not sell, share or otherwise give access to your data to any company and our site does not integrate services such as Google Analytics, Facebook Pixel, Doubleclick or similar.
At the logistical level, it will only be accessible by volunteers of the initiative <a href="https://www.accommodation-for-refugees.com/" class="text-muted">https://www.accommodation-for-refugees.com/</a> , who will then do on-the-ground matching at "Landesamt für Flüchtlingsangelegenheiten" Berlin.
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFourteen" aria-expanded="false" aria-controls="collapseFourteen">
        Who is behind this page?
      </button>
    </h2>
    <div id="collapseFourteen" class="accordion-collapse collapse" aria-labelledby="headingFourteen" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        We are an initiative of ca. 12 people who found each other via social media, sparked by discussions about the housing matching problem.
      </div>
    </div>
  </div>


  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
        How do we know the data is really used where you say it is?
      </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        We are working on implementing backlinks from the official initiatives.
      </div>
    </div>
  </div>



 <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
        Is the data encrypted? What does it mean?
      </button>
    </h2>
    <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Data flows are protected by SSL. Once the data rests on our server, it is encrypted with AES-256 block-level encryption. We make sure to scrape personal-identifiable data (such as email addresses) from our logs as well.
      </div>
    </div>
  </div>


 <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
       Is the code for your page open source?
      </button>
    </h2>
    <div id="collapseSeven" class="accordion-collapse collapse" aria-labelledby="headingSeven" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Yes, you can see it at <a href="https://github.com/Sprachprofi/safehost" class="text-muted"> https://github.com/Sprachprofi/safehost/</a>, released under CC BY-NC-SA 4.0.
      </div>
    </div>
  </div>



<div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
       Does the phone verification service also store my phone number? Or does only your site save it?
      </button>
    </h2>
    <div id="collapseEight" class="accordion-collapse collapse" aria-labelledby="headingEight" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        For billing and legal purposes, the phone verification service needs to store a list of phone numbers that it sent SMS to. However, it does not know anything about you, not even your name.
      </div>
    </div>
  </div>



<div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
      Where are your servers located?
      </button>
    </h2>
    <div id="collapseNine" class="accordion-collapse collapse" aria-labelledby="headingNine" data-bs-parent="#accordionExample">
      <div class="accordion-body">
     We are hosted with Heroku in Frankfurt, Germany.
      </div>
    </div>
  </div>







<h3 class="header-style mb-3 mt-3" >3. Supporting guests </h3>

<p>Also check the <a href="https://safehost.space/en/pages/next_steps" class="text-muted">Next steps page</a></p>

<div class="accordion accordion-flush" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTen" aria-expanded="true" aria-controls="collapseTen">
       I received guests via your site, can you help me supporting them?
      </button>
    </h2>
    <div id="collapseTen" class="accordion-collapse collapse" aria-labelledby="headingTen" data-bs-parent="#accordionExample">
      <div class="accordion-body">
 We presented some main pointers on the <a href="https://safehost.space/en/pages/next_steps" class="text-muted">Next steps page</a>, which was automatically shown after you registered your space. However, the situation changes very quickly, so we cannot do more than that or guarantee that it will be up to date when you need it, although we do our best to update. Also, maybe one Sozialamt or Behörde will decide slightly differently from another one.
      </div>
    </div>
  </div>


  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEleven" aria-expanded="false" aria-controls="collapseEleven">
        I cannot host my guests any more, can you tell me where they can go?
      </button>
    </h2>
    <div id="collapseEleven" class="accordion-collapse collapse" aria-labelledby="headingEleven" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Yes, this is unfortunately a tricky topic. It would be most logical if they searched for and found accommodation in a part of Germany or Europe where there is still long-term housing available. However, there are currently very few platforms which fulfil security requirements at least as good as this site and work quickly for such cases, which is a clear gap. While in principle, your guests could show up again on-site where data from this homepage is used, Berlin beds are also needed for new arrivals. Hence it would be great if you can monitor official advice for such cases and/or make sure they are searching via the most secure channels among those listed in Table 1 above.
      </div>
    </div>
  </div>
  </div>




<h3 class="header-style mb-3 mt-3" >4. Tech support and questions </h3>



 <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwelve" aria-expanded="false" aria-controls="collapseTwelve">
       I have a technical problem, where can I turn to?
      </button>
    </h2>
    <div id="collapseTwelve" class="accordion-collapse collapse" aria-labelledby="headingTwelve" data-bs-parent="#accordionExample">
      <div class="accordion-body">
  Contact <a href="mailto:tech@safehost.space" class="text-muted">tech@safehost.space </a>, thank you :)
    </div>
  </div>
  </div>




  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThirteen" aria-expanded="false" aria-controls="collapseThirteen">
        I know Ruby on Rails or UX/design or can offer translation and want to contribute
      </button>
    </h2>
    <div id="collapseThirteen" class="accordion-collapse collapse" aria-labelledby="headingThirteen" data-bs-parent="#accordionExample">
      <div class="accordion-body">
   Always welcome! Contact <a href="mailto:tech@safehost.space" class="text-muted">tech@safehost.space </a> , thank you :)</div>
    </div>
  </div>
  </div>







</div>

app/views/pages/index.de.html.erb
<script>
  $( document ).ready(function() {
    console.log( "jQuery is functional." );
  });
</script>
<div class="container">
  <% if @listing %>
    <div class="alert alert-info">Du bist aktuell als Gastfamilie gelistet. <%= link_to "Hier", edit_host_path(@listing) %> kannst du dein Angebot aktualisieren oder löschen.</div>
  <% end %>
  <div class="main-page">
    <div class="d-flex justify-content-center">
      <h1 class="header-style text-center">
        <span class="free-header-style fw-bold">Kostenlose </span>Privatunterkünfte für Geflüchtete
      </h1>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <span class="offers-available fs-6">Kurz- und langfristig</span>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <span class="offers-available fs-6 text-center"><b>*</b>entwickelt in enger Zusammenarbeit mit den Freiwilligen des Berliner LAF <a href="https://www.berlin.de/laf/">(Landesamt für Flüchtlingsangelegenheiten)</a>,die dein Angebot vermitteln werden</span>
    </div>
    <div class="d-flex justify-content-center mt-5">
      <%= image_tag "location.svg" %> <span class="city-name fs-4">Berlin, Deutschland</span>
    </div>
    <div class="d-flex justify-content-center mt-2 mb-5">
      <span class="offers-available fs-5"><span class="offers-quantity"><%= Host.count %></span> Unterkünfte</span>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center align-items-center">
  <div class="d-flex justify-content-evenly bg-back w-75">
    <div class="d-flex flex-column align-items-center justify-content-center w-50 bg-style big-button-card">
      <div class="big-button-card-link">
        <%= link_to t("buttons.host"), new_host_path, class: "btn btn-call-to-action", role: "button" %>
      </div>
      <div class="big-button-card-text">
        Hier kannst du eine Unterkunft für Geflüchtete anbieten.
      </div>
    </div>
    <div class="d-flex flex-column align-items-center justify-content-center w-50 bg-style big-button-card">
      <div class="big-button-card-link">
        <%= link_to t("buttons.find"), "/admin/available_hosts", class: "btn btn-call-to-action", role: "button" %>
      </div>
      <div class="big-button-card-text">
        Aktuell können sich nur Freiwilligenteams die Angebote ansehen.
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-5 mb-5">
  <span class="social-name fs-3 text-center"> Bitte teile diese Webseite mit jemandem, der helfen kann!</span>
</div>
<div class="d-flex justify-content-center">
  <div href="https://safehost.space/" id="copy-link" class="share-link d-flex flex-column align-items-center">
    <%= image_tag "share.svg", class: "mb-2" %>
    <div class="share" id="alertArea">
      Link teilen
    </div>
    <div class="link-copied d-none" id="alertText">Link wurde kopiert</div>
  </div>
</div>

app/views/pages/index.en.html.erb
<script>
  $( document ).ready(function() {
    console.log( "jQuery is functional." );
  });
</script>
<div class="container">
  <% if @listing %>
    <div class="alert alert-info">You are currently listed as a host. Review or delete your listing <%= link_to "here", edit_host_path(@listing) %>.</div>
  <% end %>
  <div class="main-page">
    <div class="d-flex justify-content-center">
      <h1 class="header-style text-center">
        <span class="free-header-style fw-bold">Free </span>private accommodation for refugees
      </h1>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <span class="offers-available fs-6">Short-term & long-term</span>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <span class="offers-available fs-6 text-center"><b>*</b>created in close collaboration with volunteers of Berlin LAF < href="https://www.berlin.de/laf/">(Landesamt für Flüchtlingsangelegenheiten)</a>, where your offers will be accepted</span>
    </div>
    <div class="d-flex justify-content-center mt-5">
      <%= image_tag "location.svg" %> <span class="city-name fs-4">Berlin, Germany</span>
    </div>
    <div class="d-flex justify-content-center mt-2 mb-5">
      <span class="offers-available fs-5"><span class="offers-quantity">499</span> accomodation offers available</span>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center align-items-center">
  <div class="d-flex justify-content-evenly bg-back w-75">
    <div class="d-flex flex-column align-items-center justify-content-center w-50 bg-style big-button-card">
      <div class="big-button-card-link">
        <%= link_to t("buttons.host"), new_host_path, class: "btn btn-call-to-action", role: "button" %>
      </div>
      <div class="big-button-card-text">
        Here you can help by offering accommodation to refugees.
      </div>
    </div>
    <div class="d-flex flex-column align-items-center justify-content-center w-50 bg-style big-button-card">
      <div class="big-button-card-link">
        <%= link_to t("buttons.find"), "/admin/available_hosts", class: "btn btn-call-to-action", role: "button" %>
      </div>
      <div class="big-button-card-text">
        Right now only volunteer teams can browse accommodation offers available to refugees.
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-5 mb-5">
  <span class="social-name fs-3 text-center"> Please share this website with someone who can help!</span>
</div>
<div class="d-flex justify-content-center">
  <div href="https://safehost.space/" id="copy-link" class="share-link d-flex flex-column align-items-center">
    <%= image_tag "share.svg", class: "mb-2" %>
    <div class="share" id="alertArea">
      Share the link
    </div>
    <div class="link-copied d-none" id="alertText">Link copied</div>
  </div>
</div>

app/views/pages/index.html.erb
<script>
  $( document ).ready(function() {
    console.log( "jQuery is functional." );
  });
</script>
<div class="container">
  <% if @listing %>
    <div class="alert alert-info">You are currently listed as a host. Review or delete your listing <%= link_to "here", edit_host_path(@listing) %>.</div>
  <% end %>
  <div class="main-page">
    <div class="d-flex justify-content-center">
      <h1 class="header-style text-center">
        <span class="free-header-style fw-bold">Free </span>private accommodation for refugees
      </h1>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <span class="offers-available fs-6">Short-term & long-term</span>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <span class="offers-available fs-6 text-center"><b>*</b>created in close collaboration with volunteers of <a href="https://www.facebook.com/berlin.laf/" target="_blank" class="link-secondary"> LAF</a>, where your offers will be accepted</span>
    </div>
    <div class="d-flex justify-content-center mt-5">
      <%= image_tag "location.svg" %> <span class="city-name fs-4">Berlin, Germany</span>
    </div>
    <div class="d-flex justify-content-center mt-2 mb-5">
      <span class="offers-available fs-5"><span class="offers-quantity">499</span> accomodation offers available</span>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center align-items-center">
  <div class="d-flex justify-content-evenly bg-back w-75">
    <div class="d-flex flex-column align-items-center justify-content-center w-50 bg-style big-button-card">
      <div class="big-button-card-link">
        <%= link_to t("buttons.host"), new_host_path, class: "btn btn-call-to-action", role: "button" %>
      </div>
      <div class="big-button-card-text">
        Here you can help by offering accommodation to refugees.
      </div>
    </div>
    <div class="d-flex flex-column align-items-center justify-content-center w-50 bg-style big-button-card">
      <div class="big-button-card-link">
        <%= link_to t("buttons.find"), "/admin/available_hosts", class: "btn btn-call-to-action", role: "button" %>
      </div>
      <div class="big-button-card-text">
        Right now only volunteer teams can browse accommodation offers available to refugees.
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-5 mb-5">
  <span class="social-name fs-3 text-center"> Please share this website with someone who can help!</span>
</div>
<div href="https://safehost.space/" id="copy-link" class="share-link">
  <div class="d-flex justify-content-center mt-5 mb-2">
    <%= image_tag "share.svg" %>
  </div>
  <div class="d-flex justify-content-center mb-5">
    <div class="share">Share the link
      <span class="link-copied d-none " id="alertArea">Link copied</span>
    </div>
  </div>
</a>
</div>