config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|de|uk|ru|fr|it|es|pt/ do

    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
    devise_for :users, controllers: {
      sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations',
      passwords: 'users/passwords', unlocks: 'users/unlocks'
    }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :hosts, except: [:index] do
      collection do
        get 'finished_signup'
      end
    end

    resources :pages, only: [:index] do
      collection do
        get 'about'
        get 'faq'
        get 'next_steps'
        get 'data_privacy'
        post 'export_my_data'
        get 'legal'
      end
    end

    get 'verifications/new' => 'verifications#new', as: :new_verification
    get 'verifications/no_phone' => 'verifications#no_phone_verify', as: :no_phone_verify
    post 'verifications/do_id_verify' => 'verifications#do_id_verify', as: :do_id_verify
    post 'verifications/send' => 'verifications#do_send_pin', as: :send_verification
    post 'verifications/check' => 'verifications#check', as: :check_verification
    get 'verifications/review' => 'verifications#review', as: :review_verifications
    match 'verifications/verify_member/:id' => 'verifications#verify_member', as: :verify_member, via: [:get, :post]
    match 'verifications/reject_verification/:id' => 'verifications#reject_verification', as: :reject_verification, via: [:get, :post]

    root to: "pages#index"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  prepend_around_action :switch_locale

  rescue_from ActionController::RoutingError, ::AbstractController::ActionNotFound, ActiveRecord::RecordNotFound do |exception|
    logger.warn "Not Found: '#{request.fullpath}'. #{exception.class} was raised: #{exception.message}"
    render 'pages/e_404', status: 404
  end

  def default_url_options
    { locale: I18n.locale }
  end
  
  def self.default_url_options
    { locale: I18n.locale }
  end

  def get_locale_from_browser
    http_accept_language.compatible_language_from(I18n.available_locales)
  end

  def require_activeadmin_privileges!
    authenticate_user! if current_user.nil?
    if current_user.has_privilege?('match_hosts_in_city') or current_user.has_privilege?('help_single_user')
      # go!
    else
      flash[:alert] = 'You do not currently have ActiveAdmin access. If you believe you should have it, e.g. to do matches, write to Judith.'
      redirect_to '/'
    end
  end
  
  def require_privilege(privilege, scope = nil)
    authenticate_user! if current_user.nil? 
    if !current_user.has_privilege?(privilege, scope)
      flash[:alert] = "This function requires you to have #{privilege} privileges, which you don't have. If you believe you should have it, write to Judith."
      redirect_to('/') and return
    else
      # render
    end
  end
  
  def switch_locale(&action)
    params[:locale] = nil if not I18n.available_locales.include?(params[:locale].try(:to_sym))
    locale = params[:locale]
    session[:locale]  = locale if params[:locale]
    if Rails.env.test?
      locale ||= :en
    else
      locale ||= (session[:locale] || get_locale_from_browser || I18n.default_locale)
    end
    I18n.with_locale(locale, &action)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def email(address, options = {})
    link_to address, "mailto:#{address}", options
  end

  def pretty_privileges(user, joiner = ', ')
    arr = []
    user.privileges.each do |priv, scope|
      if scope
        arr << (priv + ' (' + scope + ') ')
      else
        arr << priv
      end
    end
    arr.sort.join(joiner)
  end
  
  def social_link(url)
    (url = "mailto:" + url) if url.include?("@") and !url.starts_with?("http") and !url.starts_with?("mailto:")
    (url = "https://" + url) if url.starts_with?("www.")
    img = if url.include?("facebook.com")
      "some/facebook-blue.png"
    elsif url.include?("twitter.com")
      "some/twitter-blue.png"
    elsif url.include?("@") and !url.starts_with?("http")
      "some/email-green.png"
    elsif url.include?("vk.com")
      "some/vk.png"
    elsif url.include?("telegram.org") or url.include?("/t.me")
      "some/messenger-generic.png"
    elsif url.include?("reddit.com")
      "some/reddit.png"
    elsif url.include?("linkedin.com")
      "some/linkedin.png"
    elsif url.include?("instagram.com")
      "some/instagram.png"
    elsif url.include?("youtube.com") or url.include?("youtu.be")
      "some/youtube.png"
    elsif url.include?("github.com")
      "some/github.png"
    else
      "some/website.png"
    end
    raw("<a href=\"#{url}\" title=\"#{img[5..-5]}\">" + image_tag(img, height: 40, width: 40) + "</a>")
  end
  
  # Converts
  # "string with __link__ in the middle." to
  # "string with #{link_to('link', link_url, link_options)} in the middle."
  def string_with_link(str, link_url, link_options = {})
    match = str.match(/__([^_].{1,50}[^_])__/)
    if !match.blank?
      link_options[:target] = '_blank' if link_url.include?('http')
      raw($` + link_to($1, link_url, link_options) + $')
    else
      #raise "string_with_link: No place for __link__ given in #{str}" if Rails.env.development?
      str
    end
  end

  # Alternative to string_with_link for pure text emails
  # this produces e.g. "Please visit our group (https://...) in order to learn more."
  def string_without_link(str, link_url, link_options = {})
    match = str.match(/__([^_]{2,50})__/)
    if !match.blank?
      raw($` + $1 + ' (' + link_url + ')' + $')
    else
      # raise "string_with_link: No place for __link__ given in #{str}" if Rails.env.test?
      str
    end
  end

  def url(address)
    if address
      if address.include?('http') # outside link
        raw(link_to address, address, target: '_blank')
      else
        raw(link_to address, address)
      end
    end
  end
  
end

app/views/application/_footer.html.erb
<div class="container-fluid footer-info">
    <div class="container d-flex justify-content-center ">
      <footer class="row footer-info mt-5">
        <div class="first-footer-col col-12 col-md-6 col-xl-4">
          <p class="safehost-name fs-3 text-nowrap text-break">Safehost</p>
          <p class="safehost-description word-wrap font-weight-light">
            is a tool to provide a secure and verified option for hosts to register and for volunteers to find matches.
          </p>
        </div>
        <div class="d-flex justify-content-center middle-col col-12 col-md-6 col-xl-4 ">
          <ul class="list-group useful-info text-nowrap text-break">
            <li><%= link_to t("general.about_us"), about_pages_path, class: "list-group-item footer-links" %></li>
            <li><%= link_to t("general.faq"), faq_pages_path, class: "list-group-item footer-links" %></li>
            <li><%= link_to t("general.next_steps"), next_steps_pages_path, class: "list-group-item footer-links" %></li>
            <li><%= link_to t("general.legal"), legal_pages_path, class: "list-group-item footer-links" %></li>
            <li><%= link_to t("general.data_privacy"), data_privacy_pages_path, class: "list-group-item footer-links" %></li>
            <li><a class="list-group-item footer-links" href="mailto:tech@safehost.space">Contact us</a></li>
          </ul>
        </div>
        <div class="col-12 col-md-12 col-xl-4 mb-4">
          <div class="row text-center justify-content-center mt-5 mt-xl-0">
            <div class="col-12 col-sm-6 col-xl-12">
              <p class="tg-public-link fs-4">Stay tuned
            </div>
            <a href="https://t.me/+kwT7YEg1LFUxNmFi" target="_blank" class="footer-links">
              <%= image_tag "telegram.svg" %>
              <p class="mt-1 safehost-description">Telegram</p>
            </a>
            <a href="mailto:tech@safehost.space" target="_blank" class="footer-links mt-1 safehost-description">
              tech@safehost.space
            </a>
          </div>
        </div>
      </footer>
    </div>
  </div>

app/views/application/_menu.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <div class="logo-bar">
        <a class="main-logo-container d-flex align-items-end" href="/">
          <%= image_tag "logo.svg", class: "main-logo" %>
          <span class="logo-text fs-2">Safehost</span>
        </a>
      </div>
      <button class="navbar-toggler menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
        aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-grow-0" id="navbarContent">
        <div class="d-flex justify-content-lg-end flex-wrap nav-list">
          <ul class="navbar-nav ml-sm-0 ">
            <li class="nav-item "><%= link_to t("general.about_us"), about_pages_path, class: "nav-link hover-underline-animation" %></li>
            <li class="nav-item "><%= link_to t("general.faq"), faq_pages_path, class: "nav-link hover-underline-animation" %></li>
            <li class="nav-item "><%= link_to t("general.next_steps"), next_steps_pages_path, class: "nav-link hover-underline-animation" %></li>
            <% if current_user %>
              <li class="nav-item"><%= link_to "Admin", "/admin/available_hosts", class: "nav-link hover-underline-animation" %></li>
              <li class="nav-item"><%= link_to "Log out", "/users/sign_out", class: "nav-link hover-underline-animation" %></li>
            <% else %>
			  <li class="nav-item "><%= link_to t("general.sign_up"), new_host_path, class: "btn btn-secondary sign-up-item-style" %></li>
              <li class="nav-item "><%= link_to t("general.log_in"), new_user_session_path, class: "nav-link hover-underline-animation" %></li>
            <% end %>
            </li>
             <li class="nav-item "><a href="mailto:tech@safehost.space" class="nav-link  hover-underline-animation">Contact us</a></li>
            <li class="nav-item language-box ml-xl-2">
              <div class="dropdown">
                <a class="nav-link  dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  <%= t("general.language") %> <%= image_tag "Polygon.svg", class: "polygon" %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><%= link_to("Deutsch", { locale: :de}, class: "dropdown-item") %></li>
                  <li><%= link_to("English", { locale: :en}, class: "dropdown-item") %></li>
                  <li><%= link_to("Русский", { locale: :ru}, class: "dropdown-item") %></li>
                  <li><%= link_to("Українська", { locale: :uk}, class: "dropdown-item") %></li>
                </ul>
              </div>
            </li>
       
          </ul>
        </div>
      </div>
    </div>
  </nav>